[package]
name = "error"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
argon2 = "0.5"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
sea-orm = { version = "1.1.0" }
validator = { version = "0.16", features = ["derive"] }
validator_types = "0.16"
